# Generated by Django 4.1.7 on 2023-03-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('round_description', models.CharField(default='round description here', max_length=500)),
                ('download_template', models.CharField(default='https://www.bvpieee.in', max_length=500)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
