# Generated by Django 4.1.7 on 2023-03-08 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_link', models.CharField(blank=True, max_length=100)),
                ('youtube_link', models.CharField(blank=True, max_length=100)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_submission', to='portal.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_submission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.BooleanField(default=True)),
                ('youtube', models.BooleanField(default=True)),
                ('file', models.BooleanField(default=False)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_form', to='portal.round')),
            ],
        ),
    ]
