# Generated by Django 4.1.7 on 2023-03-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_submissionform_formrequirements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionform',
            old_name='github_link',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='submissionform',
            old_name='youtube_link',
            new_name='youtube',
        ),
    ]
