# Generated by Django 4.1.7 on 2023-03-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_rename_github_link_submissionform_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='next_round',
            field=models.BooleanField(default=False),
        ),
    ]
