# Generated by Django 4.1.7 on 2023-03-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_round_next_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
