# Generated by Django 4.1.7 on 2023-03-08 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_submissionform_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 0, 28, 10, 383567)),
            preserve_default=False,
        ),
    ]
