# Generated by Django 4.1.7 on 2023-03-08 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_round_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 9, 1, 9, 47, 912616)),
            preserve_default=False,
        ),
    ]
