# Generated by Django 4.1.7 on 2023-03-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_over',
            field=models.BooleanField(default=False),
        ),
    ]
