# Generated by Django 4.1.7 on 2023-03-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_round_round_over'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='next_round',
        ),
    ]
