# Generated by Django 4.1.7 on 2023-04-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_round_eligible_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teamID',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
