# Generated by Django 4.1.7 on 2023-05-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_user_teamid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_type_offline',
            field=models.BooleanField(default=False),
        ),
    ]
