# Generated by Django 4.1.7 on 2023-05-21 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_user_team_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='https://www.bvpieee.in', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_grading_sheet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
