# Generated by Django 4.1.7 on 2023-05-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_gradingsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_number',
            field=models.IntegerField(default=0),
        ),
    ]
