# Generated by Django 4.1.7 on 2023-05-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_alter_user_team_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionform',
            name='theme',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
